#大項目
version: "3"
services:
  #名前項目
  mysql000ex1:
    #詳細設定項目
    platform: linux/x86_64
    image: mysql:5.7
    networks:
      - wordpress000net1
    volumes:
      - mysql000vol1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wordpress000db
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: userpass
  wordpress000ex1:
    #詳細設定項目
    depends_on:
      - mysql000ex1
    image: wordpress
    networks:
      - wordpress000net1
    volumes:
      - wordpress000vol1:/var/www/html
    ports:
      - 8085:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql000ex1
      WORDPRESS_DB_NAME: wordpress000db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: userpass 
networks:
  wordpress000net1:
volumes:
  mysql000vol1:
  wordpress000vol1: